@Serviço.Estoque_HostAddress = https://localhost:7222

GET {{Serviço.Estoque_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Serviço.Estoque_HostAddress}}/estoque
Content-Type: application/json

{
  "Description": "Teste",
  "Balance": 999
}

###
