// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Serviço.Estoque.Data;

#nullable disable

namespace Serviço.Estoque.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605140602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Serviço.Estoque.Models.Produto", b =>
                {
                    b.Property<string>("UniqueI")
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueI");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
